name: Build Android APK

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.19.4'
          package-manager-cache: false

      # 3. Check Node.js version
      - name: Check Node.js
        run: |
          node --version
          npm --version

      # 4. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      # 5. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 6. Read app version
      - name: Read app version
        id: version
        run: |
          VERSION=$(grep -oP "(?<=APP_VERSION = ')[^']+" src/version.ts)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      # 7. Generate native Android project
      - name: Generate native Android project
        run: npx expo prebuild --platform android --clean

      # 8. Build APK
      - name: Build APK
        working-directory: ./android
        env:
          ORG_GRADLE_PROJECT_reactNativeArchitectures: arm64-v8a
        run: ./gradlew assembleRelease

      # 9. Rename APK
      - name: Rename APK
        run: |
          mv android/app/build/outputs/apk/release/app-release.apk \
             android/app/build/outputs/apk/release/homeweather_v${{ steps.version.outputs.version }}.apk

      # 10. Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: homeweather_v${{ steps.version.outputs.version }}
          path: android/app/build/outputs/apk/release/homeweather_v${{ steps.version.outputs.version }}.apk