name: Build Android APK

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1  # Version stable et non dépréciée

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2  # Version stable et non dépréciée
        with:
          node-version: 18.x
          cache: false  # Désactive le cache pour éviter l'erreur 400

      - name: Setup Java
        uses: actions/setup-java@v5  # Migration vers v5 (recommandé)
        with:
          distribution: temurin
          java-version: '17'

      - name: Install dependencies
        run: npm ci

      - name: Generate native Android project (Prebuild)
        run: npx expo prebuild --platform android --clean

      - name: Build APK (Gradle)
        working-directory: ./android
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4.3.0  # Version stable et non dépréciée
        with:
          name: homeweather-apk
          path: android/app/build/outputs/apk/release/app-release.apk